SELECT CREATOR, NAME
FROM SYSIBM.SYSTABLES
WHERE NAME LIKE '%C214%' OR NAME LIKE '%P001%'
ORDER BY CREATOR, NAME;

SELECT *
FROM SYSIBM.SYSTABLES;

SELECT TBNAME, NAME AS COLUMN_NAME, COLTYPE, LENGTH, SCALE
FROM SYSIBM.SYSCOLUMNS
WHERE (TBNAME LIKE 'S001%' OR TBNAME LIKE 'P001%')
  AND NAME LIKE '%EXCH%'
ORDER BY TBNAME, COLUMN_NAME;

select * from SYSIBM.SYSCOLUMNS
--where tbname like '%C214%'
where NAME LIKE '%EXCH%'
fetch first 1000 rows only;

select * from c406.C406B40

select * from C430.C430A40

select * from SYSIBM.SYSCOLUMNS
--where tbname like '%C214%'
where NAME LIKE '%EX%RATE%' OR NAME LIKE '%EXCH%'
fetch first 1000 rows only;

select * from c406.c406TIN
where C406TIN_VTOM_ORDER_NUM = '25401055'
